workflows:
  build-ios-unsigned:
    name: Build Unsigned iOS IPA
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter packages get
        script: flutter pub get

      - name: Build iOS release (no signing)
        script: |
          flutter build ios --release --no-codesign

      - name: Create IPA manually
        script: |
          echo "Searching for Runner.app..."
          cd build/ios
          APP_PATH=""
          if [ -d "iphoneos/Runner.app" ]; then
            APP_PATH="iphoneos/Runner.app"
          elif [ -d "Release-iphoneos/Runner.app" ]; then
            APP_PATH="Release-iphoneos/Runner.app"
          else
            echo "❌ Runner.app not found."
            exit 1
          fi

          echo "✅ Found app at: $APP_PATH"
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -r -y Runner.ipa Payload
          mkdir -p ipa
          mv Runner.ipa ipa/
          echo "🎉 IPA created successfully at: build/ios/ipa/Runner.ipa"

    artifacts:
      - build/ios/ipa/Runner.ipa
      - build/ios/**/Runner.app

    publishing:
      email:
        recipients:
          - maslamhussaini@gamil.com
