workflows:
  flutter-ios:
    name: Flutter iOS Build (Unsigned)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_NAME: "Runner"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS release
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - maslamhussasini@gmail.com
